### PR TITLE
Fixes #460: Fixes KcContext to contain attributes for client object

### LINKED ISSUE #460: KcContext for client missing attributes
The client object in KcContext is missing typing for the attributes field:
```
attributes?: Record<string, string>;
```

### PR DESCRIPTION
**Pull request by BlackVoid**

### CODE REVIEW

**Comment by garronej** [comment]
Yes,  
I think we could even loose the `?` am I right?

**Comment by BlackVoid** [comment]
I can remove it, was just unsure if it's always there or not :)

**Comment by garronej** [comment]
Yes it is.  
Thank you for adding this. It's indeed important to show pepole that this exist since it holds the environement variables which are very important when you build a customizable theme.  

Even myself was doing this:  

image

**Comment by garronej** [comment]
Releasing a new version now

**Pull request merged**
